Test.Test("Maximize and hide entergame", function(test, wait, ss, fail)
    wait(2000)
    test(function() 
        g_window.maximize()
    end)
    wait(2000)
    ss()
    test(function() 
        EnterGame.hide()
    end)
end)    

Test.Test("Login on 1098, evolunia", function(test, wait, ss, fail)
    test(function()
        g_game.setClientVersion(1098)
        g_game.setProtocolVersion(g_game.getClientProtocolVersion(1098))
        g_game.playRecord("1613922049_176.9.2.170_7172.record")
    end)
    wait(5000)
    ss()
    wait(1000)
    wait(5000)
    ss()
    wait(5000)
    ss()
    wait(5000)
    ss()
    wait(5000)
    ss()
    test(function()
        if not g_game.isOnline() then
            fail("Should be online")
        end
        g_game.forceLogout()    
    end)
    wait(1000)
    ss()
    test(function()
        if g_game.isOnline() then
            fail("Shouldn't be online")
        end
    end)
end)

Test.run()
